get_random_seed      <- import_future("get_random_seed")
set_random_seed      <- import_future("set_random_seed")
next_random_seed     <- import_future("next_random_seed")
is_valid_random_seed <- import_future("is_valid_random_seed")
is_lecyer_cmrg_seed  <- import_future("is_lecyer_cmrg_seed")
as_lecyer_cmrg_seed  <- import_future("as_lecyer_cmrg_seed")
